import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul className={`${styles["unstyled-list"]} text-center`}>
          <li>
            <Link href="/users" className='no-link'>Users</Link>
          </li>
          <li>
            <Link href="/products" className='no-link'>Products</Link>
          </li>
          <li>
            <Link href="/products/add-product" className='no-link'>Add Product</Link>
          </li>
          <li>
            <Link href="/admins" className='no-link'>Admins</Link>
          </li>
        </ul>
      </main>
    </>
  )
}

export default Home;
